### ISSUE TITLE
Navbar Is Transparent On Mobile Devices

### ISSUE THREAD

**Issue by rohit-rambade** [nkowaokwu/igbo_api#685]
**Describe the bug**
Navbar is Transparent In Sign Up page . Can't see options.

**To Reproduce**
1. Go to 'https://igboapi.com/'
2. Switch To Mobile View. e.g Pixel 5
3. Click on 'Get an API Key' you will redirected to "https://igboapi.com/signup"
4. Open Navbar 
5. See Issue

**Screenshots**
![image](https://github.com/nkowaokwu/igbo_api/assets/86614477/58b5003b-a2fb-4329-948c-7f977f6cca16)
![image](https://github.com/nkowaokwu/igbo_api/assets/86614477/7a606030-4a75-4a24-8ca4-4549494bf04d)

**Expected behavior**
![image](https://github.com/nkowaokwu/igbo_api/assets/86614477/013b2f80-fe7f-40ef-aac2-0996796831cb)

**Comment by PeaceOloruntoba** [comment]
check in the source code, and set the text-color

**Comment by PeaceOloruntoba** [comment]
I just viewed the web view and if you noticed the text-color is set to white, just change it to any color of you choice but not white 

or 

you set the media screen in css and @mediascreen mobile screen size, set the color to maybe green, or your preferred color

**Comment by pauluzo** [comment]
Hello @ijemmao I'd love to work on this issue. 
I've forked the repo and cloned it too. While running yarn build, I run into an error that I can't seem to get past. Can I get some community support to help resolve that? Thanks.

Here is the yarn build error faced: 

**failing command**
 shx cp -r ./src/dictionaries/ig-en ./dist/dictionaries/ig-en && shx cp -r ./src/dictionaries/en-ig ./dist/dictionaries/en-ig

**error**
cp: cannot create directory './dist/dictionaries/ig-en': No such file or directory

**Comment by ijemmao** [comment]
@pauluzo thanks for taking this on ✨ this is definitely not the solution, but can you create a directory called dist in the top level of the project directory and then run the build command again?

Let me know if that works or not so I can update either our getting started docs or our build scripts

**Comment by pauluzo** [comment]
@ijemmao thanks for having me on. I tried your solution, but still got the same error. I'm highlighting some of the things I noticed: 

1. The build command deletes any current dist folder (the one I created) and then creates another one during the build process.
2. I watched the dist folder during the build process and realized that new files/folders were being copied into the folder successfully before that particular command failed
3. The two previous commands that ran successfully are: **shx cp -r ./src/pages/assets/ ./dist/assets** and **shx cp -r ./src/public/fonts/ ./dist/fonts** so it seems that the issue with this command is because the ./dist folder does not have a "dictionaries" subfolder yet, so second level copying is not working, while first level copying seems to have no issue. (not certain about this).

**Comment by ijemmao** [comment]
@pauluzo that's an interesting bug since I thought I thought I fixed it and this error doesn't occur in our CI pipeline. Just to confirm, what OS are you using?

**Comment by pauluzo** [comment]
@ijemmao my PC runs on a windows 10

**Comment by ijemmao** [comment]
yeah, i believe there's an npm script that doesn't run well on windows - you can create a separate bug ticket so another person can help fix it!

**Comment by Ebugo** [comment]
Hi @ijemmao, is this issue already assigned or can I jump on it?

**Comment by ijemmao** [comment]
@Ebugo it's been assigned to you! feel free to ask questions

**Comment by Ebugo** [comment]
@ijemmao Okay, will dive right in.. I'll def reach out if I encounter a blocker, thanks.
